print("Twinkle Twinkle Little Star,")
print("\tHow I wonder what you are!")
print("\tUp above the world so high,")
print("\tLike a diamond in the sky.")
print("Twinkle Twinkle Little Star,")
print("\tHow I wonder what you are!")